name: Add Wallpaper from Unsplash

on:
  workflow_dispatch:
    inputs:
      unsplash_url:
        description: 'Unsplash image URL'
        required: true
        type: string

permissions:
  contents: write

jobs:
  add-wallpaper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download wallpaper from Unsplash
        shell: bash
        run: |
          mkdir -p wallpapers
          fname="wallpapers/$(date +%s).jpg"
          wget "${{ github.event.inputs.unsplash_url }}" -O "$fname"

      - name: Commit and push new wallpaper
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add new wallpaper from Unsplash"
          file_pattern: wallpapers/*
