name: Add Wallpaper from Unsplash

on:
  workflow_dispatch:
    inputs:
      unsplash_url:
        description: 'Unsplash image URL'
        required: true
        type: string

jobs:
  add-wallpaper:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download wallpaper from Unsplash
      run: |
        URL="${{ github.event.inputs.unsplash_url }}"
        
        # Extract image ID from Unsplash URL
        if [[ "$URL" =~ unsplash\.com/photos/([^/?]+) ]]; then
          IMAGE_ID="${BASH_REMATCH[1]}"
        else
          echo "Invalid Unsplash URL format"
          exit 1
        fi
        
        # Download the image (using raw format for best quality)
        RAW_URL="https://unsplash.com/photos/${IMAGE_ID}/download?force=true"
        
        # Try to get the original filename from the response headers, otherwise use image ID
        FILENAME=$(curl -sI "$RAW_URL" | grep -i 'content-disposition' | sed -n 's/.*filename="\([^"]*\)".*/\1/p' || echo "${IMAGE_ID}.jpg")
        
        # If no filename found, use image ID with jpg extension
        if [ -z "$FILENAME" ] || [ "$FILENAME" = "${IMAGE_ID}.jpg" ]; then
          FILENAME="${IMAGE_ID}.jpg"
        fi
        
        # Download the image
        echo "Downloading $URL as $FILENAME"
        curl -L -o "$FILENAME" "$RAW_URL"
        
        # Verify the file was downloaded
        if [ ! -f "$FILENAME" ]; then
          echo "Failed to download image"
          exit 1
        fi
        
        echo "Successfully downloaded: $FILENAME"
        ls -la "$FILENAME"
        
    - name: Commit and push new wallpaper
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.jpg *.jpeg *.png *.webp
        if git diff --staged --quiet; then
          echo "No new wallpapers to commit"
        else
          git commit -m "Add wallpaper from Unsplash: ${{ github.event.inputs.unsplash_url }}"
          git push
        fi
        
    - name: Trigger wallpaper indexing
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'index-wallpapers.yml'
          })